# Generated by Django 3.2.12 on 2024-01-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20240123_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='fixed',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=100),
        ),
    ]
