# Generated by Django 3.2.12 on 2024-01-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_0005_appointment_user_0007_remove_pet_adopted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
    ]
