# Generated by Django 3.2.12 on 2024-01-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('shots_recieved', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('fixed', models.BooleanField()),
            ],
        ),
    ]
