# Generated by Django 3.2.12 on 2024-01-20 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='shots_recieved',
            new_name='shots_received',
        ),
    ]
