# Generated by Django 5.0.1 on 2024-01-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_pet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
