# Generated by Django 5.0.1 on 2024-01-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_breed_pet_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='fixed',
        ),
    ]
