# Generated by Django 3.2.12 on 2024-01-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_pet_adopted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='Adopted',
        ),
    ]
