# Generated by Django 5.0.1 on 2024-01-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_pet_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='user',
        ),
    ]
