# Generated by Django 3.2.12 on 2024-01-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_appointment_user'),
        ('main_app', '0007_remove_pet_adopted'),
    ]

    operations = [
    ]
