# Generated by Django 5.0.1 on 2024-01-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_pet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='fixed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
