# Generated by Django 5.0.1 on 2024-01-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_pet_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='fixed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='user',
        ),
    ]
