# Generated by Django 5.0.1 on 2024-01-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_pet_fixed_pet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
